"""
Phase 5 — AI interpretation routes.

POST /api/worlds/{world_id}/agents/{agent_id}/ask
  Ask an agent a question; receive an in-character answer.
  Degrades gracefully when AI is disabled or unavailable.
"""
from __future__ import annotations

from fastapi import APIRouter, HTTPException
from sqlalchemy import select
from sqlalchemy.orm import selectinload

from app.ai.schemas import AgentContextData
from app.api.deps import DbSession
from app.core.config import settings
from app.models.db import Agent, World
from app.schemas import AskAgentRequest, AskAgentResponse

router = APIRouter()


# ---------------------------------------------------------------------------
# Profession-specific opener lines (first-person, present-tense)
# ---------------------------------------------------------------------------

_PROF_OPENERS: dict[str, str] = {
    "farmer":     "The harvest waits for no one.",
    "healer":     "There is always someone who needs my care.",
    "soldier":    "I keep watch so others may sleep sound.",
    "merchant":   "I have trades to settle before sundown.",
    "blacksmith": "The forge demands all of me.",
    "priest":     "My prayers and duties fill every hour.",
    "elder":      "The burdens of this village sit heavy on my shoulders.",
    "scholar":    "My studies press upon me.",
    "hunter":     "The forest will not wait.",
    "carpenter":  "There is always something to mend.",
}


def _deceased_response(ctx: AgentContextData) -> str:
    """
    Deterministic memorial response for dead agents.

    Never calls AI. Returns the same text regardless of question asked —
    dead agents have no voice in the present, only a record in the chronicle.
    """
    return (
        f"{ctx.agent_name} is no longer among the living. "
        f"The {ctx.profession} passed from this world, "
        "and their story has been written into the chronicle."
    )


def _fallback_answer(ctx: AgentContextData) -> str:
    """
    Deterministic, context-aware in-character fallback when AI is unavailable.

    Priority order:
      0. Deceased — always returns memorial text (overrides everything below)
      1. Sick and very hungry (most urgent stress)
      2. Sick alone
      3. Very hungry alone
      4. Hungry
      5. Grudge relationship (most notable foe)
      6. Recent memory
      7. Alliance relationship
      8. Generic close

    Never hallucinates — only uses data present in ctx.
    """
    if not ctx.is_alive:
        return _deceased_response(ctx)
    opener = _PROF_OPENERS.get(ctx.profession, "I have much to attend to.")

    sick = any("ill" in r for r in ctx.pressure_reasons)
    very_hungry = any("very hungry" in r for r in ctx.pressure_reasons)
    hungry = any("hungry" in r for r in ctx.pressure_reasons) and not very_hungry

    if sick and very_hungry:
        detail = "I am ill and starving — I beg you, not now."
    elif sick:
        detail = "I am not well. I cannot speak long."
    elif very_hungry:
        detail = "I am famished. My thoughts scatter. Ask me again when I have eaten."
    elif hungry:
        detail = "My belly reminds me I have not eaten enough. I must see to that."
    else:
        foe = next((r for r in ctx.relationships if r.get("status") == "foe"), None)
        ally = next((r for r in ctx.relationships if r.get("status") == "ally"), None)

        if foe:
            detail = f"My thoughts are troubled — matters with {foe['name']} weigh on me."
        elif ctx.recent_memories:
            mem = ctx.recent_memories[-1].rstrip(".")
            detail = f"{mem}. That still sits with me."
        elif ally:
            detail = f"I am grateful for {ally['name']}'s help of late, but I must press on."
        else:
            detail = "Perhaps another time."

    return f"I am {ctx.agent_name}, the {ctx.profession}. {opener} {detail}"


@router.post(
    "/{world_id}/agents/{agent_id}/ask",
    response_model=AskAgentResponse,
    summary="Ask an agent a question (AI-powered, degrades gracefully)",
)
async def ask_agent(
    world_id: int,
    agent_id: int,
    body: AskAgentRequest,
    db: DbSession,
):
    """
    Ask a village agent a question and receive an in-character answer.

    The answer is generated by Claude using the agent's personality traits,
    goals, relationships, recent memories, and current pressure context.

    When AI is disabled (ai_enabled=false) or unavailable, a deterministic
    fallback answer is returned and `fallback=true` is set in the response.
    The fallback varies meaningfully by agent: profession, hunger/sickness,
    grudges, and recent memories are all reflected.
    """
    # Load world
    world = await db.get(World, world_id)
    if world is None:
        raise HTTPException(status_code=404, detail=f"World {world_id} not found")

    # Load agent with relevant associations
    stmt = (
        select(Agent)
        .where(Agent.id == agent_id, Agent.world_id == world_id)
        .options(
            selectinload(Agent.inventory),
            selectinload(Agent.memories),
            selectinload(Agent.outgoing_relationships),
        )
    )
    result = await db.execute(stmt)
    agent = result.scalar_one_or_none()
    if agent is None:
        raise HTTPException(
            status_code=404,
            detail=f"Agent {agent_id} not found in world {world_id}",
        )

    # Build name map (single cheap query; needed for rich fallback and AI path)
    name_result = await db.execute(
        select(Agent.id, Agent.name).where(Agent.world_id == world_id)
    )
    name_map: dict[int, str] = {row.id: row.name for row in name_result}

    # Build compact context — used by both the AI path and the fallback
    from app.ai.context_builder import build_agent_context_from_orm
    context = build_agent_context_from_orm(agent, world, name_map)

    # Dead-agent guard: deceased agents never respond as living agents.
    # This check supersedes AI, fallback, pressure, and relationship context.
    if not agent.is_alive:
        return AskAgentResponse(
            agent_id=agent_id,
            agent_name=agent.name,
            answer=_deceased_response(context),
            ai_enabled=settings.ai_enabled,
            fallback=True,
            agent_deceased=True,
        )

    # Fast path: AI disabled — rich deterministic fallback
    if not settings.ai_enabled or not settings.ai_ask_agent_enabled:
        return AskAgentResponse(
            agent_id=agent_id,
            agent_name=agent.name,
            answer=_fallback_answer(context),
            ai_enabled=False,
            fallback=True,
        )

    # Call AI service
    from app.ai.service import ai_service
    ai_resp = await ai_service.ask_agent(context, body.question)

    if ai_resp is None:
        return AskAgentResponse(
            agent_id=agent_id,
            agent_name=agent.name,
            answer=_fallback_answer(context),
            ai_enabled=settings.ai_enabled,
            fallback=True,
        )

    return AskAgentResponse(
        agent_id=agent_id,
        agent_name=agent.name,
        answer=ai_resp.answer,
        ai_enabled=True,
        fallback=False,
    )
